name: hanguk_app
description: Hanguk Academy DRM Cross-Platform App
publish_to: 'none'

version: 1.0.3+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Provides WebView capabilities to wrap the Vercel web app
  webview_flutter: ^4.4.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_filex: ^4.3.4
  package_info_plus: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
