import { Video, BookOpen, Clock } from "lucide-react";

export default function StudentDashboard() {
  return (
    <div className="flex flex-col gap-8 max-w-5xl mx-auto">
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">My Overview</h1>
        <p className="text-slate-400">Welcome back! You are on track with your 3x/week curriculum.</p>
      </div>

      {/* Up Next Card */}
      <div className="glass-card p-6 md:p-8 rounded-2xl border border-brand-500/30 flex flex-col md:flex-row items-center justify-between gap-6 shadow-[0_0_30px_rgba(45,212,191,0.1)]">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-brand-500/10 text-brand-400 rounded-full text-sm font-medium mb-4">
            <Clock className="w-4 h-4" /> Starting in 45 mins
          </div>
          <h2 className="text-2xl font-bold text-white mb-2">Beginner Korean - Cohort B</h2>
          <p className="text-slate-400">Topic: Formal greetings & Verb Conjugation.</p>
        </div>
        <button className="group px-8 py-4 bg-brand-500 text-surface-900 font-bold rounded-xl hover:bg-brand-400 flex items-center gap-2 transition-all w-full md:w-auto text-center justify-center">
          <Video className="w-5 h-5" /> Join Live Classroom
        </button>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {/* Recent AI Notes */}
        <div className="glass-card p-6 rounded-2xl border border-slate-700/50">
          <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-brand-400" /> Recent AI Notes
          </h3>
          <div className="flex flex-col gap-3">
            {[1, 2, 3].map((i) => (
              <div key={i} className="p-4 bg-slate-800/50 rounded-xl hover:bg-slate-700/50 transition-colors cursor-pointer border border-slate-700/30">
                <div className="font-semibold text-slate-200">Lesson {i}: Vocabulary Extract</div>
                <div className="text-sm text-slate-500 mt-1">Generated by GPT-4o • 2 days ago</div>
              </div>
            ))}
          </div>
        </div>

        {/* Progress */}
        <div className="glass-card p-6 rounded-2xl border border-slate-700/50">
          <h3 className="text-lg font-bold text-white mb-4">Weekly Goal</h3>
          <div className="flex items-center gap-4 mb-4">
            <div className="w-full bg-slate-800 rounded-full h-4 overflow-hidden border border-slate-700">
              <div className="bg-brand-500 h-full rounded-full" style={{ width: "66%" }}></div>
            </div>
            <span className="text-white font-bold">2/3</span>
          </div>
          <p className="text-slate-400 text-sm">
            You've attended 2 out of 3 live sessions this week. Don't miss your final class to maintain your streak!
          </p>
        </div>
      </div>
    </div>
  );
}
